import type { ResumeData } from "../types";

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Build Word-compatible HTML document from resume data. */
export function buildResumeDocxHtml(resumeData: ResumeData): string {
  const title = resumeData.personalInfo.name || "Resume";
  const contactInfo = [
    resumeData.personalInfo.email,
    resumeData.personalInfo.phone,
    resumeData.personalInfo.location,
    resumeData.personalInfo.website,
  ]
    .filter(Boolean)
    .join(" | ");

  return `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head>
      <title>${escapeHtml(title)} - CV</title>
      <!--[if gte mso 9]>
      <xml>
        <w:WordDocument>
          <w:View>Print</w:View>
          <w:Zoom>100</w:Zoom>
          <w:DoNotOptimizeForBrowser/>
        </w:WordDocument>
      </xml>
      <![endif]-->
      <style>
        body { font-family: 'Calibri', 'Arial', sans-serif; line-height: 1.35; padding: 1in; color: #333333; }
        h1 { font-size: 24pt; font-weight: bold; margin: 0 0 4pt 0; text-align: center; text-transform: uppercase; color: #111111; }
        .subtitle { font-size: 11pt; text-align: center; margin-bottom: 20pt; color: #555555; }
        .section-title { font-size: 13pt; font-weight: bold; border-bottom: 1px solid #777777; text-transform: uppercase; margin-top: 18pt; margin-bottom: 8pt; color: #1e3a8a; }
        .summary { margin-bottom: 12pt; text-align: justify; font-size: 10.5pt; }
        .bullet-item { margin-left: 15pt; text-indent: -10pt; font-size: 10.5pt; margin-bottom: 4pt; }
        .skills-list { font-size: 10.5pt; line-height: 1.5; }
      </style>
    </head>
    <body>
      <h1>${escapeHtml(resumeData.personalInfo.name || "Name")}</h1>
      <div class="subtitle">
        <strong>${escapeHtml(resumeData.personalInfo.title || "")}</strong><br/>
        ${escapeHtml(contactInfo)}
      </div>
      <div class="section-title">Professional Summary</div>
      <div class="summary">${escapeHtml(resumeData.summary || "No professional summary provided.")}</div>
      <div class="section-title">Technical Skills</div>
      <div class="skills-list"><strong>Skills:</strong> ${escapeHtml(resumeData.skills.join(", ") || "None listed.")}</div>
      <div class="section-title">Work Experience</div>
      ${resumeData.experience
        .map(
          (exp) => `
        <table width="100%" style="margin-bottom: 8pt; font-size:11pt; font-family:'Calibri',sans-serif;">
          <tr>
            <td align="left"><strong>${escapeHtml(exp.role)}</strong> - ${escapeHtml(exp.company)}</td>
            <td align="right" style="text-align: right;">${escapeHtml([exp.startDate, exp.endDate].filter(Boolean).join(" – ") || "")} | ${escapeHtml(exp.location || "")}</td>
          </tr>
        </table>
        ${exp.bullets.map((b) => `<div class="bullet-item">• ${escapeHtml(b)}</div>`).join("")}
      `
        )
        .join("")}
      ${
        resumeData.projects?.length
          ? `<div class="section-title">Projects</div>
      ${resumeData.projects
        .map(
          (proj) => `
        <table width="100%" style="margin-bottom: 4pt; font-size:11pt; font-family:'Calibri',sans-serif;">
          <tr>
            <td align="left"><strong>${escapeHtml(proj.name)}</strong>${proj.techStack ? ` (${escapeHtml(proj.techStack)})` : ""}</td>
            <td align="right" style="text-align: right;">${escapeHtml(proj.url || "")}</td>
          </tr>
        </table>
        <div class="summary">${escapeHtml(proj.description)}</div>
      `
        )
        .join("")}`
          : ""
      }
      <br/>
      <hr style="border: none; border-top: 1px dotted #bbbbbb;"/>
      <p style="font-size: 8pt; color:#999999; text-align:center;">
        Generated by NextStepResume.ai Elite Workspace Optimizer.
      </p>
    </body>
    </html>
  `;
}

export function downloadDocxFromHtml(html: string, filename: string): void {
  const blob = new Blob(["\ufeff" + html], {
    type: "application/msword;charset=utf-8",
  });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  const safeName = filename.replace(/\.docx$/i, "").replace(/\.doc$/i, "");
  link.download = `${safeName}.doc`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function downloadResumeDocx(resumeData: ResumeData, filenameBase = "resume"): void {
  const html = buildResumeDocxHtml(resumeData);
  const name = resumeData.personalInfo.name || filenameBase;
  downloadDocxFromHtml(html, `${name.replace(/\s+/g, "_")}_CV.doc`);
}
